services:
  - type: web
    name: baghayeneh-bot
    env: python
    runtime: python-3.12.8
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
